### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by djjudas21** [camptocamp/puppetfile-updater#1]
Hi, sorry to raise an issue for what's really a lame support request :disappointed: 

I'm experienced with Puppet but only started using r10k this week and I have no idea how to use rake. I added the code snippet from your `README` to a Rakefile like this:

``` ruby
task :update do
  require 'puppetfile-updater/task'

  # Update all modules, avoid major version updates
  PuppetfileUpdater::RakeTask.new :sync_refs do |config|
    # This is required to avoid hitting the GitHub connection rate
    config.gh_login    = 'github_robot'
    config.gh_password = 'github_password'
  end
end
```

I've put this Rakefile in the same directory as the Puppetfile and I'm trying to run the task by doing `rake update`. It returns no output, no errors, etc. Am I doing the right thing?

Thanks,
Jonathan

**Comment by djjudas21** [comment]
I added a `desc` line which now means the task is recognised by `rake -T`. Still doesn't work though:

``` ruby
desc "Update Puppet modules from Puppet Forge and GitHub"
task :update => :environment do
  require 'puppetfile-updater/task'

  # Update all modules, avoid major version updates
  PuppetfileUpdater::RakeTask.new :sync_refs do |config|
    # This is required to avoid hitting the GitHub connection rate
    config.gh_login    = 'github_robot'
    config.gh_password = 'github_password'
  end
end
```

```
[jg4461@it050546 resnet-puppet]$ rake update
rake aborted!
Don't know how to build task 'environment'

Tasks: TOP => update
(See full trace by running task with --trace)
```

Any clues?

**Comment by raphink** [comment]
@djjudas21 You don't have to create rake tasks yourself, the `PuppetfileUpdater::RakeTask` call does that. So the example in the README is all you need, nothing else. If you want to name the task with another name than `sync_ref`, you can do so, too.

**Comment by raphink** [comment]
In your case:

``` ruby
  require 'puppetfile-updater/task'
  PuppetfileUpdater::RakeTask.new :update do |config|
    # This is required to avoid hitting the GitHub connection rate
    config.gh_login    = 'github_robot'
    config.gh_password = 'github_password'
  end
```

and you can then call `rake update`

**Comment by djjudas21** [comment]
Thanks, I think I understand rake a little better now. It does not throw any errors but it doesn't make any changes to the `Puppetfile`, so I think it is still not working. Any hints?

**Comment by raphink** [comment]
Do you expect any updates on this Puppetfile?

**Comment by djjudas21** [comment]
Yes. Some of the modules have newer releases on the Puppet Forge

**Comment by raphink** [comment]
Can you show your Puppetfile (or at least those entries) so I can test?

**Comment by djjudas21** [comment]
One example entry is this. `1.7.1` is available on the Forge.

``` ruby
mod 'puppetlabs/firewall','1.7.0'
```

**Comment by raphink** [comment]
It works for me here, the module gets updated.

**Comment by djjudas21** [comment]
So the expected behaviour is that the `Puppetfile` gets updated?

**Comment by raphink** [comment]
I wonder if maybe your Puppetfile fails to parse. Can you send the entire Puppetfile, maybe in a gist?

**Comment by djjudas21** [comment]
OK, here's the gist: https://gist.github.com/djjudas21/e6947e530fdf7e25b2cf

For what it's worth, r10k parses it without complaining.

**Comment by raphink** [comment]
I just release 0.3.0 which fails when parsing fails (see #2) and adds a verbose option (see #3).

Now I'll fix the lens so that it does fail to parse your file…

**Comment by djjudas21** [comment]
Oh, so there was a mistake in my Puppetfile. Thanks for your fixes.
I'm going home now but I will test this tomorrow morning at work.

**Comment by raphink** [comment]
No, I think your syntax was fine, my parser was wrong, so I fixed it.

Version 0.3.1 is now on the forge and is able to parse and update your Puppetfile.

A few notes on it though:
- for the wordpress module, you're pointing `ref` to a branch. This is not recommended, you should point to a commit instead (which is what the updater will do)
- for the logrotate module, you're using `commit` instead of `ref`. The updater will add `ref` to it, but I would recommend you don't use `commit` at all

**Comment by djjudas21** [comment]
Awesome, thanks.

Thanks for the tips, too. My team and I are experienced with Puppet but new
to the r10k workflow and still have a few issues to work out.
